- name: Add Postgres metrics
  become: true
  command: "/usr/sbin/pmm-admin add postgresql {{ pmm_alias | default(inventory_hostname) }} --user={{ pmm_postgres_username }} --password={{ pmm_postgres_password }}"
  when: ('postgresql:metrics' not in pmm_existing_services.stdout)
  register: postgres_metrics

- name: Restart Prometheus client (Postgres metrics)
  become: true
  service:
    name: "pmm-postgresql-metrics-{{ postgres_metrics_port }}"
    state: restarted
    enabled: yes
  when: (postgres_metrics is defined and postgres_metrics.changed) or (pmm_version_running is defined and pmm_version_running.changed)
