
- set_fact:
    pmm_mongodb_username: "{{ pmm_client_mongo_username }}"
    pmm_mongodb_password: "{{ pmm_client_passwd }}"

- set_fact:
    mongo_uri: --uri "{{ pmm_mongodb_username }}":"{{ pmm_mongodb_password }}"@"{{ inventory_hostname }}.{{ env }}.recurly.net":27017
  when: pmm_mongo_auth

- set_fact:
    mongo_uri: ""
  when: not pmm_mongo_auth

- set_fact:
    mongo_ssl: "-- --mongodb.tls --mongodb.tls-ca={{ mongo_ssl_ca_file }} --mongodb.tls-cert={{ mongo_ssl_pem_file }}"
  when: pmm_mongo_ssl

- set_fact:
    mongo_ssl: ""
  when: not pmm_mongo_ssl

- name: Add mongodb metrics
  command:  /usr/sbin/pmm-admin add mongodb:metrics {{ pmm_alias | default(inventory_hostname) }} {{ mongo_uri }} {{ mongo_ssl }}
  when: ('mongodb:metrics' not in pmm_existing_services.stdout)
  register: mongodb_metrics

- name: Add mongodb QAN
  command:  /usr/sbin/pmm-admin add mongodb:queries {{ pmm_alias | default(inventory_hostname) }} {{ mongo_uri }}
  when: ('mongodb:queries' not in pmm_existing_services.stdout) and not pmm_mongo_ssl
  register: mongodb_queries

- name: Restart Prometheus client (MongoDB metrics)
  service:
    name: "pmm-mongodb-metrics-{{ mongodb_metrics_port }}"
    state: restarted
    enabled: yes
  when: (mongodb_metrics is defined and mongodb_metrics.changed) or (pmm_version_running is defined and pmm_version_running.changed)

- name: Restart MongoDB QAN
  command: "/usr/sbin/pmm-admin restart mongodb:queries {{ pmm_alias | default(inventory_hostname) }}"
  when: (mongodb_queries is defined and mongodb_queries.changed) or (pmm_version_running is defined and pmm_version_running.changed)

 #  --uri "{{ pmm_mongodb_username }}:{{ pmm_mongodb_passwd }}@{{ pmm_mongodb_host | default('localhost') }}:{{ pmm_mongodb_port | default('27017') }}"
