---
- set_fact:
    pmm_server_ip: "{{ pmm_server_hostname }}"
  when: pmm_server_ip is undefined

- set_fact:
    pmm_server_port: 8443
    pmm_server_ssl: --server-insecure-ssl
  when: pmm_ssl_enabled

- set_fact:
    pmm_server_port: 8080
    pmm_server_ssl: ""
  when: not pmm_ssl_enabled

- name: Python dependencies
  become: true
  yum:
    name: python-ssl
    state: present
  when: ansible_distribution in ['CentOS','RedHat','Oracle', 'Scientific'] and ansible_distribution_version < 6

- name: Check pmm-client running version
  become: true
  command: /usr/sbin/pmm-admin --version
  register: pmm_version_running
  ignore_errors: yes
  changed_when: (pmm_version_running.rc == 0 and pmm_version_running.stdout is version_compare(pmm_install_version, '!='))

- name: Install pmm-client (RedHat family & Amazon)
  become: true
  yum:
    name: "pmm-client-{{ pmm_install_version }}"
    state: present
    allow_downgrade: yes
    allow_unauthenticated: yes
  when: ansible_distribution in ['CentOS','RedHat','Oracle', 'Scientific', 'Amazon']

- name: Install pmm-client (Debian family)
  become: true
  apt:
    name: "pmm-client={{ [ pmm_install_version, '-1.', ansible_lsb.codename ] | join('') }}"
    state: present
  environment:
    DEBIAN_FRONTEND: noninteractive
  when: ansible_os_family == 'Debian'

- name: Install percona-toolkit (Debian family)
  become: true
  apt:
    name: percona-toolkit
    state: present
  when: ansible_os_family == 'Debian'

- name: check for orphaned services
  become: true
  command: /usr/sbin/pmm-admin list
  register: pmm_orphaned_services
  no_log: no
  changed_when: ('Orphaned local services' in pmm_orphaned_services.stdout) or ('Orphaned remote services' in pmm_orphaned_services.stdout)
  failed_when: (pmm_orphaned_services.rc > 0) and not pmm_orphaned_services.changed and (not 'PMM client is not configured' in pmm_orphaned_services.stdout) and (not 'However, PMM server is not' in pmm_orphaned_services.stdout)
  ignore_errors: true

- name: repair services
  become: true
  command: /usr/sbin/pmm-admin repair
  no_log: no
  when: pmm_orphaned_services.changed

- name: check for incorrect configuration
  become: true
  command: /usr/sbin/pmm-admin list
  register: pmm_incorrect_config
  no_log: no
  changed_when: ('Unable to connect to PMM server by address' in pmm_incorrect_config.stdout_lines[0]) and (pmm_server_ip not in pmm_incorrect_config.stdout_lines[0])
  failed_when: (pmm_incorrect_config.rc > 0) and not pmm_incorrect_config.changed
  when: ('PMM client is not configured' not in pmm_orphaned_services.stdout) and ('However, PMM server is not' not in pmm_orphaned_services.stdout)

- name: reset configuration
  become: true
  command: /usr/sbin/pmm-admin uninstall
  no_log: no
  when: pmm_incorrect_config.changed

#- name: Get Metadata for Server
#  uri:
#    url: "metadata.google.internal/computeMetadata/v1/instance/attributes/description' -H 'Metadata-Flavor: Google"
#    return_content: yes
#    register: pmm_alias

- name: Get Metadata For Server
  become: true
  command: "curl 'metadata.google.internal/computeMetadata/v1/instance/attributes/pmm-client-description' -H 'Metadata-Flavor: Google'"
  register: curl_output

- set_fact:
    pmm_alias: "{{ curl_output.stdout }}"
  when: curl_output.stdout != '0' and '404' not in curl_output.stdout 

- name: Check existing services
  become: true
  command: /usr/sbin/pmm-admin list
  register: pmm_existing_services
  no_log: no
  changed_when: ('PMM client is not configured' in pmm_existing_services.stdout) or ('No services under monitoring' in pmm_existing_services.stdout) or (pmm_existing_services.rc > 0 and 'Unable to connect to PMM server by address' in pmm_existing_services.stdout_lines[0]) or ('However, PMM server is not' in pmm_existing_services.stdout) or (pmm_alias | default(ansible_hostname) not in pmm_existing_services.stdout)
  failed_when: ( pmm_existing_services.rc > 0) and ('PMM client is not configured' not in pmm_existing_services.stdout) and ('No services under monitoring' not in pmm_existing_services.stdout) and ('However, PMM server is not' not in pmm_existing_services.stdout)
  ignore_errors: yes

- name: Remove servics if something has changed
  become: true 
  command: "/usr/sbin/pmm-admin remove --all"
  when: pmm_existing_services.changed
  ignore_errors: yes

  # Removing auth line : --server-user {{ pmm_server_username }} --server-password {{ pmm_server_password }}  , also removed :{{ pmm_server_port }} as it is not needed and was blocking config execution
- name: Check/configure PMM
  become: true 
  command: "/usr/sbin/pmm-admin config --client-name '{{ pmm_alias | default(ansible_hostname) }}' --client-address {{ ansible_default_ipv4.address }} --server {{ pmm_server_ip }} {{ pmm_server_ssl }} --force"
  when: (pmm_version_running.changed or pmm_version_running.rc > 0 or pmm_existing_services.changed) 

- name: Check existing services (Again)
  become: true
  command: /usr/sbin/pmm-admin list
  register: pmm_existing_services
  no_log: no
  changed_when: ('PMM client is not configured' in pmm_existing_services.stdout) or ('No services under monitoring' in pmm_existing_services.stdout) or (pmm_existing_services.rc > 0 and 'Unable to connect to PMM server by address' in pmm_existing_services.stdout_lines[0]) or ('However, PMM server is not' in pmm_existing_services.stdout)
  failed_when: ( pmm_existing_services.rc > 0) and ('PMM client is not configured' not in pmm_existing_services.stdout) and ('No services under monitoring' not in pmm_existing_services.stdout) and ('However, PMM server is not' not in pmm_existing_services.stdout)
  ignore_errors: yes

- name: Add Linux metrics
  become: true
  command: "/usr/sbin/pmm-admin add linux:metrics {{ pmm_alias | default(ansible_hostname) }} --service-port={{ linux_metrics_port }} -- {{ pmm_client_node_exporter_extra_args | join(' ') }}"
  when: ('linux:metrics' not in pmm_existing_services.stdout)
  register: linux_metrics

- name: percona-agent present
  become: true
  stat:
    path: /usr/local/percona/percona-agent
  register: percona_agent_present

- name: Disable percona-agent if present
  become: true
  service:
     name: percona-agent
     state: stopped
     enabled: no
  when: percona_agent_present.stat.exists == True

- name: Restart Prometheus client (Linux metrics)
  become: true
  service:
    name: "pmm-linux-metrics-{{ linux_metrics_port }}"
    state: restarted
    enabled: yes
  when: linux_metrics.changed or pmm_version_running.changed

# tasks file for pmm-client by group

- name: popualte server facts
  service_facts:

- include_tasks: manage-mysql.yml
  when: "'mysql' in ansible_facts.services and 'running' in ansible_facts.services['mysql'].state"

- include_tasks: manage-proxysql.yml
  when: "'proxysql' in ansible_facts.services and 'running' in ansible_facts.services['proxysql'].state"

- include_tasks: manage-mongodb.yml
  when: "'mongod' in ansible_facts.services and 'running' in ansible_facts.services['mongod'].state"

- include_tasks: manage-postgres.yml
  when: "'postgresql' in ansible_facts.services and 'running' in ansible_facts.services['postgresql'].state"
